config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
root :to => 'homes#top'#トップページ
get 'books'=> 'books#index' #一覧および新規投稿
post 'books' => 'books#create'
get 'books/:id' => 'books#show',as: 'book'#詳細ページ
get 'books/:id/edit' => 'books#edit',as: 'edit_book'#編集ページ
patch 'books/:id' => 'books#update',as: 'update_book'
delete 'books/:id' => 'books#destroy',as: 'destroy_book'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
   @book = Book.new
   @books = Book.all
  end

  def create
   @book = Book.new(book_params)
   if @book.save
   redirect_to book_path(@book.id)
   else
    @books = Book.all
   render :index
   end
   flash[:create] ="Book was successfully created!"
  end

  def show
  @book = Book.find(params[:id])
  end

  def edit
   @book = Book.find(params[:id])
  end


  def update
  @book = Book.find(params[:id])
  if @book.update(book_params)
    redirect_to book_path(@book.id)
  else
    render :edit
  end
  flash[:update] = "Book was successfully update!"
  end

  def destroy
  book = Book.find(params[:id])
  book.destroy
  redirect_to '/books'
  flash[:delete] ="Book was successfully destroyed."
  end


 private
  def book_params
  params.require(:book).permit(:title,:body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<% if @book.errors.any? %>
 <%= @book.errors.count %> errors prohibited this book from being saved:
 <ul>
   <% @book.errors.full_messages.each do |message| %>
   <li><%= message %></li>
   <% end %>
<% end %>

<h1>Editing Book</h1>
<%= form_with model: @book,url: update_book_path(@book.id),local:true do |f| %>

<div class = "field">
<h4>Title</h4>
<%= f.text_field :title %>
</div>

<div class = "field">
<h4>Body</h4>
<%= f.text_area :body %>
</div>
<br><%= f.submit 'Update Book' %></br>
<p class ="show"><%= link_to "Show" ,book_path(@book.id)%>| <a href ="/books">Back</a></p>

<% end %>

app/views/books/index.html.erb
<body>
  <p id = "notice"><%= flash[:delete] %></p>
<h1>Books</h1>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>
<tbody>
  <% @books.each do |book| %>
    <td><%= book.title %></td>
    <td><%= book.body %></td>
    <td><%= link_to "Show",book_path(book.id) %></td>
    <td><%= link_to "Edit",edit_book_path(book.id) %></td>
    <td><%= link_to "Destroy",destroy_book_path(book.id),method: :delete,"data-confirm" => "Are you sure?" %></td>
  </tr>
  <% end %>
</tbody>
</table>

<% if @book.errors.any? %>
 <%= @book.errors.count %> errors prohibited this book from being saved:
 <ul>
   <% @book.errors.full_messages.each do |message| %>
   <li><%= message %></li>
   <% end %>
 </ul>
 <% end %>
<h2>New book</h2>
<%= form_with model: @book, local:true do |f| %>

<div class = "field">
<h4>Title</h4>
  <%= f.text_field :title %>
</div>

<div class = "field">
<h4>Body</h4>
<%= f.text_area :body %>
</div>

<div class = "actions">
<br><%= f.submit 'Create Book'%></br>
</div>

<% end %>
</body>

app/views/books/show.html.erb
<body>
<%= flash[:create] %>
<%= flash[:update] %>
 <p class ="title"><strong>Title:</strong> <%= @book.title %></p>

 <p class ="body"><strong>Body:</strong> <%= @book.body %></p>

 <p><%= link_to "Edit",edit_book_path(@book.id) %> |<a href ="/books">Back</a></p>
</body>

app/views/homes/top.html.erb
<body>
<h1>ようこそ <strong>Bookers</strong> へ！</h1>
 <p class = "text"><strong>Bookers</strong> では、さまざまな書籍に関するあなたの意見や</p>
 <p class ="text">印象を共有し交換することができます</p>

 <!---start押したら/booksへ飛ぶようにする-->
 <p><a href ="/books">start</a></p>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class= main>
    <%= yield %>
    </div>
  </body>
</html>